force-app/main/default/objects/SObjectAutomationHandler__mdt/SObjectAutomationHandler__mdt.object-meta.xml
<CustomObject>
    <description
  >Individual handler for execution automation on SObjects.</description>
    <label>SObject Automation Handler</label>
    <pluralLabel>SObject Automation Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/SObjectAutomationHandler__mdt/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <description
  >The class name (Apex) for API name (flow) for the automation to run.</description>
    <inlineHelpText
  >The class name (Apex) for API name (flow) for the automation to run.</inlineHelpText>
    <label>Api Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectAutomationHandler__mdt/fields/AutomationType__c.field-meta.xml
<CustomField>
    <fullName>AutomationType__c</fullName>
    <description>The type of automation to run this handler as.</description>
    <inlineHelpText
  >The type of automation to run this handler as.</inlineHelpText>
    <label>Automation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
                <default>true</default>
                <label>Apex</label>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContextAutomationHandlerFactory.cls
/**
 * @description Creates automation handlers based on the SObject for which the automation is executing and the
 * context for which the automation is executing in. Refer to {@link IAutomationHandlerFactory} for more details
 *
 * @group Automation
 */
public inherited sharing class ContextAutomationHandlerFactory implements IAutomationHandlerFactory {
  @TestVisible
  private static final String APEX_STRING = 'Apex';
  @TestVisible
  private static final String FLOW_STRING = 'Flow';

  @TestVisible
  private AutomationSelector selector {
    get {
      if (this.selector == null) {
        this.selector = new AutomationSelector();
      }
      return this.selector;
    }
    set;
  }
  @TestVisible
  private Schema.SObjectType sObjType;
  @TestVisible
  private System.TriggerOperation op;

  /**
   * @description Constructor
   * @param sObjType [Schema.SObjectType](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_Schema_SObjectType.htm) to load automation for
   */
  public ContextAutomationHandlerFactory(
    Schema.SObjectType sObjType,
    System.TriggerOperation op
  ) {
    this.sObjType = sObjType;
    this.op = this.op;
  }

  /**
   * @description Creates and returns the handlers to be used based on injected sobject type and
   * automation context
   * @see IAutomationHandlerFactory
   * @return List of {@link IAutomationHandler} instances to execute
   */
  public List<IAutomationHandler> createHandlers() {
    List<IAutomationHandler> handlers = new List<IAutomationHandler>();
    List<SObjectAutomationHandler__mdt> activeHandlers = this.selector.getAutomationHandlerConfig(
      this.sObjType,
      this.op
    );
    for (SObjectAutomationHandler__mdt config : activeHandlers) {
      if (config.AutomationType__c == APEX_STRING) {
        handlers.add(
          (IAutomationHandler) Type.forName(config.ApiName__c).newInstance()
        );
      } else if (config.AutomationType__c == FLOW_STRING) {
        handlers.add(new FlowAutomationHandler(config.ApiName__c));
      }
    }
    return handlers;
  }
}