force-app/main/default/objects/SObjectAutomationHandler__mdt/SObjectAutomationHandler__mdt.object-meta.xml
<CustomObject>
    <description
  >Individual handler for execution automation on SObjects.</description>
    <label>SObject Automation Handler</label>
    <pluralLabel>SObject Automation Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/SObjectAutomationHandler__mdt/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <description
  >The class name (Apex) for API name (flow) for the automation to run.</description>
    <inlineHelpText
  >The class name (Apex) for API name (flow) for the automation to run.</inlineHelpText>
    <label>Api Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectAutomationHandler__mdt/fields/AutomationType__c.field-meta.xml
<CustomField>
    <fullName>AutomationType__c</fullName>
    <description>The type of automation to run this handler as.</description>
    <inlineHelpText
  >The type of automation to run this handler as.</inlineHelpText>
    <label>Automation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
                <default>true</default>
                <label>Apex</label>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SObjectAutomationHandler__mdt/fields/BeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>BeforeInsert__c</fullName>
    <description
  >The SObject subscriber to register this handler with for before insert contexts.</description>
    <inlineHelpText
  >The SObject subscriber to register this handler with for before insert contexts.</inlineHelpText>
    <label>Before Insert</label>
    <referenceTo>SObjectAutomationSubscriber__mdt</referenceTo>
    <relationshipLabel>Before Insert Handlers</relationshipLabel>
    <relationshipName>BeforeInsertHandlers</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/SObjectAutomationHandler__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not the handler is active.</description>
    <inlineHelpText>Whether or not the handler is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SObjectAutomationHandler__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description
  >The priority to execute handlers with. Lower numbers will be executed first and null values will be executed last.</description>
    <inlineHelpText
  >The priority to execute handlers with. Lower numbers will be executed first and null values will be executed last.</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SObjectAutomationSubscriber__mdt/SObjectAutomationSubscriber__mdt.object-meta.xml
<CustomObject>
    <description
  >Configuration that registers an SObject to work with the automation framework.</description>
    <label>SObject Automation Subscriber</label>
    <pluralLabel>SObject Automation Subscribers</pluralLabel>
</CustomObject>

force-app/main/default/objects/SObjectAutomationSubscriber__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not the subscriber is active.</description>
    <inlineHelpText>Whether or not the subscriber is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SObjectAutomationSubscriber__mdt/fields/SObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>SObjectApiName__c</fullName>
    <description
  >The API name of the SObject to register for automation.</description>
    <inlineHelpText
  >The API name of the SObject to register for automation.</inlineHelpText>
    <label>SObject Api Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AutomationSelector.cls
/**
 * @description Basic selector to separate query functionality. Does not rely on any
 * proper selector frameworks to avoid introducing any library dependencies
 *
 * @group Automation
 */
public inherited sharing class AutomationSelector {
  @TestVisible
  private static final String QUERY_STRING =
    'SELECT ApiName__c, AutomationType__c FROM SObjectAutomationHandler__mdt WHERE ' +
    'IsActive__c = true AND {0} = {1} ORDER BY Priority__c ASC NULLS LAST';

  /**
   * @description Returns active automation config for the provided sobject type
   * and trigger context
   * @param sObjType [Schema.SObjectType](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_Schema_SObjectType.htm) to load automation for
   * @param op [System.TriggerOperation](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_TriggerOperation.htm) for which automation should execute
   * @return List of configuration for the provided sobject/operation
   */
  public List<SObjectAutomationHandler__mdt> getAutomationHandlerConfig(
    Schema.SObjectType sObjType,
    System.TriggerOperation op
  ) {
    return (List<SObjectAutomationHandler__mdt>) Database.query(
      String.format(
        QUERY_STRING,
        new List<String>{
          this.getRelationshipApiName(op),
          '\'' +
          String.valueOf(sObjType) +
          '\''
        }
      )
    );
  }

  /**
   * @description Helper to parse a trigger operation to get the appropriate cross object field to filter on for automation
   * @param op [System.TriggerOperation](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_TriggerOperation.htm) for which automation should execute
   * @return String representation of cross object field e.g. BeforeInsert__r.SObjectApiName__c
   */
  @TestVisible
  private String getRelationshipApiName(System.TriggerOperation op) {
    return String.valueOf(op).replace('_', '') + '__r.SObjectApiName__c';
  }
}